"use client";

import { X, Download, FileText, History } from "lucide-react";
import { useGetAssignmentSubmissionHistoryQuery } from "../../Api/adminApi";

const HISTORY_BADGE = {
  approved: "bg-green-100 text-green-700",
  rejected: "bg-red-100 text-red-700",
  pending: "bg-yellow-100 text-yellow-700",
  superseded: "bg-gray-100 text-gray-500",
};

export default function AssignmentDetailsModal({
  submission,
  onClose,
  onGrade,
}) {
  const { data: historyData } = useGetAssignmentSubmissionHistoryQuery(submission?.id, {
    skip: !submission?.id,
  });
  const pastAttempts = (historyData || []).filter((row) => row.id !== submission?.id);

  if (!submission) return null;

  const handleDownload = (file) => {
    // If file already has a URL, open it. Otherwise create a placeholder blob and trigger download.
    try {
      if (file.url) {
        window.open(file.url, "_blank");
        return;
      }

      const blob = new Blob(
        [
          `Placeholder content for ${file.name} \n\nThis is a demo file generated by AssignmentDetailsModal.`,
        ],
        { type: "text/plain" },
      );
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = file.name;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Download failed", err);
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        {/* Teal Header */}
        <div className="bg-teal-500 text-white p-6 flex items-center justify-between sticky top-0">
          <div>
            <h2 className="text-2xl font-bold">{submission.assignmentTitle}</h2>
            <p className="text-teal-100 mt-1">{submission.courseName}</p>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-teal-600 rounded-lg transition-colors"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-8">
          {/* Student Information */}
          <div>
            <h3 className="text-lg font-bold text-gray-900 mb-4">
              Student Information
            </h3>
            <div className="grid grid-cols-2 gap-6">
              <div>
                <p className="text-sm font-semibold text-gray-600 mb-1">
                  Student Name
                </p>
                <p className="text-gray-900 font-medium">
                  {submission.studentName}
                </p>
              </div>
              <div>
                <p className="text-sm font-semibold text-gray-600 mb-1">
                  Email
                </p>
                <p className="text-gray-900 font-medium">
                  {submission.studentEmail}
                </p>
              </div>
              <div className="col-span-2">
                <p className="text-sm font-semibold text-gray-600 mb-1">
                  Submitted Date
                </p>
                <p className="text-gray-900 font-medium">
                  {submission.submittedDate}
                </p>
              </div>
            </div>
          </div>

          {/* Student Comments */}
          <div>
            <h3 className="text-lg font-bold text-gray-900 mb-4">
              Student Comments
            </h3>
            <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
              <p className="text-gray-700 leading-relaxed">
                {submission.studentComments}
              </p>
            </div>
          </div>

          {/* Submitted Files */}
          <div>
            <h3 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
              <FileText className="w-5 h-5 text-teal-600" />
              Submitted Files ({submission.files?.length || 0})
            </h3>
            <div className="space-y-3">
              {submission.files && submission.files.length > 0 ? (
                submission.files.map((file, index) => (
                  <div
                    key={index}
                    className="flex items-center justify-between p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
                  >
                    <div className="flex items-center gap-3">
                      <FileText className="w-5 h-5 text-gray-400" />
                      <div>
                        <p className="font-medium text-gray-900">{file.name}</p>
                        <p className="text-sm text-gray-500">{file.size}</p>
                      </div>
                    </div>
                    <button
                      onClick={() => handleDownload(file)}
                      className="p-2 hover:bg-gray-200 rounded-lg transition-colors text-teal-600"
                    >
                      <Download className="w-5 h-5" />
                    </button>
                  </div>
                ))
              ) : (
                <p className="text-gray-500 text-center py-4">
                  No files submitted
                </p>
              )}
            </div>
          </div>

          {/* Previous Attempts */}
          {pastAttempts.length > 0 && (
            <div>
              <h3 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
                <History className="w-5 h-5 text-teal-600" />
                Previous Attempts ({pastAttempts.length})
              </h3>
              <div className="space-y-3">
                {pastAttempts.map((attempt) => (
                  <div
                    key={attempt.id}
                    className="p-4 border border-gray-200 rounded-lg space-y-3"
                  >
                    <div className="flex items-center justify-between">
                      <p className="text-sm font-medium text-gray-900">
                        {attempt.created_at
                          ? new Date(attempt.created_at).toLocaleString()
                          : "—"}
                      </p>
                      <span
                        className={`px-3 py-1 rounded-full text-xs font-semibold ${
                          HISTORY_BADGE[attempt.status] || HISTORY_BADGE.pending
                        }`}
                      >
                        {attempt.status}
                      </span>
                    </div>
                    {attempt.submission_text && (
                      <p className="text-sm text-gray-700 leading-relaxed">
                        {attempt.submission_text}
                      </p>
                    )}
                    {attempt.submission_file ? (
                      <div className="flex items-center justify-between p-3 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
                        <div className="flex items-center gap-3 min-w-0">
                          <FileText className="w-4 h-4 text-gray-400 shrink-0" />
                          <p className="text-xs text-gray-600 truncate">
                            {attempt.submission_file.split("/").pop()}
                          </p>
                        </div>
                        <button
                          onClick={() => handleDownload({ name: attempt.submission_file.split("/").pop(), url: attempt.submission_file })}
                          className="shrink-0 p-1.5 hover:bg-gray-200 rounded-lg transition-colors text-teal-600"
                        >
                          <Download className="w-4 h-4" />
                        </button>
                      </div>
                    ) : (
                      <p className="text-xs text-gray-400">No file submitted</p>
                    )}
                    {attempt.teacher_feedback && (
                      <p className="text-xs text-gray-500">{attempt.teacher_feedback}</p>
                    )}
                    {attempt.mark != null && (
                      <p className="text-xs text-gray-500">Mark: {attempt.mark}</p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="sticky bottom-0 bg-gray-50 p-6 border-t border-gray-200 flex gap-3">
          <button
            onClick={onClose}
            className="flex-1 px-4 py-2 text-gray-700 bg-white border border-gray-300 hover:bg-gray-50 rounded-lg font-medium transition-colors"
          >
            Close
          </button>
          <button
            onClick={() => onGrade?.(submission)}
            className="flex-1 px-4 py-2 text-white bg-teal-600 hover:bg-teal-700 rounded-lg font-medium transition-colors flex items-center justify-center gap-2"
          >
            <span>Grade Assignment</span>
          </button>
        </div>
      </div>
    </div>
  );
}
